### PR TITLE
Fixes issue 4

### LINKED ISSUE #4: Gateway support
In cntlm.conf, adding:
`Gateway yes`
and zero or more:
`Allow <ip or cidr>`

would allow using cntlm from all or specific IPs that are external to the local host.

### PR DESCRIPTION
**Pull request by holmesb**
Fixes #4

### CODE REVIEW

**Comment by robertdebock** [comment]
Looks like a great addition, thanks!

I'll let CI test your proposal, could take another day or so, I've pushed many changes yesterday.

Thanks @holmesb!

**Comment by robertdebock** [comment]
There is a (very minor) issue with your pull request:
https://travis-ci.org/robertdebock/ansible-role-cntlm/jobs/608254384#L268

No newline at the end of a file.

If you're able to fix it, great, otherwise give me a few days to pick this up.

**Review by holmesb — COMMENTED** [review]
removing trailing line-space from README.md

**Comment by robertdebock** [comment]
Looks good, one distro fails, but I'll take care of that later. Thank!

**Pull request merged**
